### ISSUE TITLE
[BUG]本地/在线装插件均失败

### ISSUE THREAD

**Issue by naruuu-xx** [lizhuangs/picgo-plugin-gitee-uploader#16]
**描述bug**
picgo 2.30 beta 7 版本

本地安装以及picgo内在线安装该插件 均会报这个错误 我没有动过这个安装文件 但是每次它总会显示缺少index js 文件
Error: Cannot find module 'C:\Users\xueto\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Function.Module._resolveFilename (C:\Program Files\PicGo\resources\electron.asar\common\reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at PluginLoader.getPlugin (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\lib\PluginLoader.js:125:24)
    at PluginLoader.registerPlugin (C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\lib\PluginLoader.js:78:26)
    at C:\Program Files\PicGo\resources\app.asar\node_modules\picgo\dist\src\lib\PluginHandler.js:40:43
-------Error Stack End------- 

我去这个路径下也找了 但是发现只有index ts文件 并没有index js 文件  电脑装过node js npm也可正常运行
![image](https://user-images.githubusercontent.com/75790544/136644489-7a1745b4-43cd-43b7-92ef-9da0bef57365.png)

**Comment by insistandinsist** [comment]
碰到同样的问题，原因是没有安装typescript。先执行 ```npm install typescript -g```，再用在线安装试试

**Comment by naruuu-xx** [comment]
感谢楼上的朋友提出的建议，我本人最后通过了把电脑切换成
![image](https://user-images.githubusercontent.com/75790544/151655146-bfb39814-3d12-4342-9c6a-6fc9c0301be4.png)
管理员账户 再安装picgo 再安装插件才成功。我当初的问题最终是由于用户权限不够导致的无法安装，使用管理员账户可解决此问题。

**Comment by cspcoding** [comment]
我也遇到类似的问题，win10专业版，picgo2.3.1正式版，已经做过pm install typescript -g，验证已装上。也用管理员administrator账户登录，删除以前所有东西，以管理员身份重装picgo，发现插件设置里列表空空如也。也搜不到git，一直转圈圈，然后就不了了之。 离线安装也仍然说安装失败和安装成功。看日志仍然是找不到index.js，只有ts文件。脑壳痛~~~搞了一天了……

**Comment by cspcoding** [comment]
C:\Users\Administrator>npm -v
10.2.5
C:\Users\Administrator>node -v
v20.10.0

**Comment by unishuai** [comment]
你好，我也遇到了类似的问题，请问您这个问题解决了吗？目前我也没有找到合理的解决办法
