### ISSUE TITLE
[BUG]Cannot read property 'webContents' of null

### ISSUE THREAD

**Issue by jay763190097** [lizhuangs/picgo-plugin-gitee-uploader#6]
```
[PicGo SUCCESS]: 
https://gitee.com/jay763190097/myhomepage/raw/master/images/2020/07/%E6%88%AA%E5%9B%BE%E5%BD%95%E5%B1%8F_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20200627000227.png
(node:16673) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'webContents' of null
    at xt (/tmp/.mount_PicGo-o6QXdU/resources/app.asar/background.js:16:35102)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:16673) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'webContents' of null
    at xt (/tmp/.mount_PicGo-o6QXdU/resources/app.asar/background.js:16:35102)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:16673) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16673) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16673) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16673) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by lizhuangs** [comment]
你这个错误貌似不是gitee插件报的，更像是pigco本身的错误，而且我看你的gitee仓库中现在已经上传成功了。请问是解决了吗？

**Comment by jay763190097** [comment]
应该是我配置的我问题，customurl的使用没看懂。现在用的是customPath + path配置的
